version: "3.8"

services:
  web:
    build: .
    restart: always
    volumes:
      - ./src:/app/src
      - ./alembic.ini:/app/alembic.ini
      - ./alembic:/app/alembic
    env_file:
      - ${ENV_FILE:-.env.local}
    expose:
      - "8000"
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    
  database:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - ${ENV_FILE:-.env.local}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust


volumes:
  postgres_data: